name: cogntix_flutter_forms
description: "A comprehensive Flutter package providing customizable, reusable form widgets with built-in validation for text fields, phone numbers, dropdowns, date/time pickers, and more."
repository: "https://github.com/Cogntix/flutter_cogntix_libraries"
version: 0.0.8

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  phone_form_field: ^9.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - form-fields
  - phone-form-field
  - date-time-picker
  - dropdown
  - custom-widgets

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:


license: MIT